---
title: "Homework_6"
author: "Abel Demoz"
format: pdf
---

```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


## Use asuupy 

```{r}
Drug_PI <- function(pdb) {   ## takes the pdb data point as the input 
  s <- read.pdb(pdb)         ## reads the pdb file 
  s_chain <- trim.pdb(s, chain="A", elety= "CA")   ## performs a specfic trim function of siad pdb file (which idk how it works)
  
  s_b <- s_chain$atom$b     ## performs atom specfic on said chain 
  plotb3(s_b, sse=s_chain, typ="l", ylab="Bfactor")   ## plots the accession site of said specific structure

}
```

```{r}
Drug_PI("4AKE")
```
```{r}
Drug_PI("1AKE")
```
```{r}
Drug_PI("1E4Y")
```